OTHER_TARGETS= buildObjc
OTHER_GARBAGE= buildObjc
MYSQL_LIBS= -L/usr/lib64/mysql -L/usr/lib/mysql -lmysqlclient
SYBASE_LIBS=-lct
OTHER_LIBS=-lClearLake -lobjc -lz -lcrypt -lcrypto \
        -lpiclib -lm -ljpeg -lpng -lpthread -lgmp -lpcre -ltiff -lutil \
	$(MYSQL_LIBS) $(SYBASE_LIBS)

